version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - '3000:8080'
    environment:
      - SWAGGER_JSON=/doc/api-bidbay.yaml
    volumes:
      - ./doc/:/doc
